- name: Get changed project folders
  id: changed
  run: |
    echo "##[group]Finding changed folders"
    git fetch origin ${{ github.event.before }}
    CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.cs$' | xargs -n1 dirname | sort -u)
    echo "Changed folders: $CHANGED_FOLDERS"
    echo "folders=$CHANGED_FOLDERS" >> $GITHUB_OUTPUT
    echo "##[endgroup]"

- name: Find and build .csproj in changed folders
  if: steps.changed.outputs.folders != ''
  run: |
    for folder in ${{ steps.changed.outputs.folders }}; do
      echo "Looking for .csproj in $folder"
      for proj in $(find "$folder" -name '*.csproj'); do
        echo "Building $proj"
        dotnet build "$proj"
      done
    done

- name: No projects changed
  if: steps.changed.outputs.folders == ''
  run: echo "No code changes detected."
