name: Dotnet CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Get changed projects
      id: changed
      run: |
        git fetch origin ${{ github.event.before }}
        CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.csproj$' | xargs)
        echo "changed=$CHANGED" >> $GITHUB_OUTPUT

    - name: Build changed projects
      if: steps.changed.outputs.changed != ''
      run: |
        for proj in ${{ steps.changed.outputs.changed }}; do
          echo "Building $proj"
          dotnet build "$proj"
        done

    - name: No projects changed
      if: steps.changed.outputs.changed == ''
      run: echo "No .csproj changes detected."
