name: Build and Run .NET Projects

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Detect changed folders
        id: changed
        run: |
          echo "##[group]Finding folders with changed .cs files"
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            echo "Previous commit exists, using HEAD^"
            CHANGED=$(git diff --name-only HEAD^ HEAD | grep '\.cs' | awk -F/ '{print $1"/"$2}' | sort -u)
          else
            echo "No previous commit (first push or force-push), using all files"
            CHANGED=$(git ls-files '*.cs' | awk -F/ '{print $1"/"$2}' | sort -u)
          fi
          echo "Changed folders: $CHANGED"
          echo "folders=$CHANGED" >> $GITHUB_OUTPUT
          echo "##[endgroup]"

      - name: Build and run changed projects
        run: |
          echo "CHANGED_FOLDERS: ${{ steps.changed.outputs.folders }}"
          IFS=$'\n'
          for folder in ${{ steps.changed.outputs.folders }}; do
            echo "Checking $folder for .csproj files"
            for proj in $(find "$folder" -maxdepth 1 -name '*.csproj'); do
              echo "Building $proj"
              dotnet build "$proj"
              # Check if it's an Exe, only run if executable
              OUTPUT_TYPE=$(grep '<OutputType>' "$proj" | sed -n 's:.*<OutputType>\(.*\)</OutputType>.*:\1:p')
              echo "OutputType: $OUTPUT_TYPE"
              if [ "$OUTPUT_TYPE" = "Exe" ]; then
                echo "Running $proj"
                dotnet run --project "$proj"
              else
                echo "Skipping run for $proj because it's a class library."
              fi
            done
          done
